apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
 name: intel-sriov-node-policy-dpdk-vfio
 namespace: openshift-sriov-network-operator
spec:
 resourceName: intelnics01
 nodeSelector:
  node-role.kubernetes.io/with-sriov: ""
 priority: 99
 mtu: 9000
 numVfs: 50
 nicSelector:
  vendor: "8086"
  deviceID: "158b"
  pfNames: ["ens1f0#0-24"]
 deviceType: vfio-pci
